ALTER TABLE branches
    ADD COLUMN IF NOT EXISTS morning_slot_capacity INTEGER NOT NULL DEFAULT 12,
    ADD COLUMN IF NOT EXISTS afternoon_slot_capacity INTEGER NOT NULL DEFAULT 12,
    ADD COLUMN IF NOT EXISTS evening_slot_capacity INTEGER NOT NULL DEFAULT 8;
